import { tags } from "typia";

/**
 * Delivery tracking information for orders including shipment statuses,
 * delivery stages, expected dates, and timestamps. Supports partial and
 * multi-stage shipments.
 *
 * @author AutoBE - https://github.com/wrtnlabs/autobe
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallDelivery = {
  /** Unique identifier of the delivery record. */
  id: string & tags.Format<"uuid">;

  /** Order ID to which this delivery belongs. */
  shopping_mall_order_id: string & tags.Format<"uuid">;

  /**
   * Current status of delivery like 'preparing', 'shipping', 'delivered',
   * 'exception'.
   */
  delivery_status: string;

  /** Delivery stage: 'preparation', 'manufacturing', 'shipping', 'completed'. */
  delivery_stage: string;

  /**
   * Expected delivery date, if applicable.
   *
   * Nullable for unknown or flexible dates.
   */
  expected_delivery_date?: string | null | undefined;

  /** Stage start datetime, nullable. */
  start_time?: string | null | undefined;

  /** Stage end datetime, nullable. */
  end_time?: string | null | undefined;

  /** Timestamp when this delivery record was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp when this delivery record was updated. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IShoppingMallDelivery {
  /**
   * Page request data
   *
   * @author AutoBE - https://github.com/wrtnlabs/autobe
   */
  export type IRequest = {
    /** Filter by delivery status (optional). */
    delivery_status?: string | null | undefined;

    /** Filter by delivery stage (optional). */
    delivery_stage?: string | null | undefined;

    /**
     * Pagination - page number.
     *
     * Must be positive integer.
     */
    page?: number | null | undefined;

    /**
     * Pagination - number of records per page.
     *
     * Default is 100.
     */
    limit?: number | null | undefined;

    /** Sort by field, optional. */
    orderBy?: string | null | undefined;

    /** Sort direction (asc or desc), optional. */
    orderDirection?: string | null | undefined;
  };

  /**
   * Request schema for creating a new delivery record.
   *
   * @author AutoBE - https://github.com/wrtnlabs/autobe
   */
  export type ICreate = {
    /** Order ID to which this delivery belongs. */
    shopping_mall_order_id: string & tags.Format<"uuid">;

    /** Current status of the delivery. */
    delivery_status: string;

    /** Current stage of delivery. */
    delivery_stage: string;

    /** Expected delivery date in ISO 8601 format, optional. */
    expected_delivery_date?: string | null | undefined;

    /** Stage start time in ISO 8601 format, optional. */
    start_time?: string | null | undefined;

    /** Stage end time in ISO 8601 format, optional. */
    end_time?: string | null | undefined;
  };

  /** Update payload for modifying details of a shopping mall delivery record. */
  export type IUpdate = {
    /**
     * Current status of delivery such as 'preparing', 'shipping',
     * 'delivered', 'exception'.
     *
     * Represents the overall delivery state in the shipment lifecycle.
     */
    delivery_status: string;

    /**
     * Stage of delivery process including 'preparation', 'manufacturing',
     * 'shipping', 'completed'.
     *
     * Indicates detailed progress within the delivery lifecycle.
     */
    delivery_stage: string;

    /**
     * Expected date/time for delivery completion.
     *
     * Nullable. May be null if no specific estimate is available.
     */
    expected_delivery_date?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /**
     * Timestamp when this delivery stage started.
     *
     * Nullable. Records the start of current stage.
     */
    start_time?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Timestamp when this delivery stage ended.
     *
     * Nullable. Records the completion of current stage.
     */
    end_time?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary information of delivery records for orders.
   *
   * Provides essential identifiers and status fields for quick reference
   * during shipment tracking.
   *
   * Supports pagination and filtering in user interfaces.
   */
  export type ISummary = {
    /** Unique delivery identifier. */
    id: string & tags.Format<"uuid">;

    /** Order ID associated with the delivery. */
    shopping_mall_order_id: string & tags.Format<"uuid">;

    /** Current status of the delivery. */
    delivery_status: string;

    /** Current stage in the delivery process. */
    delivery_stage: string;

    /** Expected delivery date, nullable if not known. */
    expected_delivery_date?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** Timestamp of creation. */
    created_at: string & tags.Format<"date-time">;
  };
}
