import { tags } from "typia";

/**
 * Individual coupon ticket records assigned to customers. These represent
 * issued coupon instances with their own validity, usage status, and linkage to
 * customers and coupons. Tickets enable tracking of coupon usage per customer
 * independent of the global coupon usage.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallCouponTicket = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** Associated coupon's unique identifier. */
  shopping_mall_coupon_id: string & tags.Format<"uuid">;

  /** Guest user owner ID, nullable for member/seller/admin ownership. */
  guestuser_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Member user owner ID, nullable for guest/seller/admin ownership. */
  memberuser_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Seller user owner ID, nullable for guest/member/admin ownership. */
  selleruser_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Admin user owner ID, nullable for guest/member/seller ownership. */
  adminuser_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Unique code for this coupon ticket. */
  ticket_code: string;

  /** Start datetime for the ticket's validity. */
  valid_from: string & tags.Format<"date-time">;

  /** End datetime for the ticket validity. */
  valid_until: string & tags.Format<"date-time">;

  /** Current usage status of the ticket (unused, used, expired). */
  usage_status: string;

  /** Datetime when ticket was used, nullable if unused. */
  used_at?: (string & tags.Format<"date-time">) | null | undefined;

  /** Record creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Record last update timestamp. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IShoppingMallCouponTicket {
  /** Filtering and pagination parameters for coupon ticket searches. */
  export type IRequest = {
    /** Coupon ID */
    shopping_mall_coupon_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Guest user ID */
    guestuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Member user ID */
    memberuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Seller user ID */
    selleruser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Admin user ID */
    adminuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Ticket code string */
    ticket_code?: string | null | undefined;

    /** Usage status */
    usage_status?: string | null | undefined;

    /** Filter valid from start */
    valid_from_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter valid until end */
    valid_from_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter valid until start */
    valid_until_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter valid until end */
    valid_until_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Page number */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /** Page size */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /** Include total count flag */
    with_count?: boolean | null | undefined;
  };

  /**
   * Coupon ticket creation record for associating coupons with registered
   * customers. Contains validity date-time range, usage status, and uniquely
   * assigned ticket codes, accounting for guests, members, sellers, and
   * admins.
   */
  export type ICreate = {
    /** Associated coupon's unique identifier. */
    shopping_mall_coupon_id: string & tags.Format<"uuid">;

    /** Guest user owner ID, nullable for member/seller/admin ownership. */
    guestuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Member user owner ID, nullable for guest/seller/admin ownership. */
    memberuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Seller user owner ID, nullable for guest/member/admin ownership. */
    selleruser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Admin user owner ID, nullable for guest/member/seller ownership. */
    adminuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Unique code for this coupon ticket. */
    ticket_code: string;

    /** Start datetime for the ticket's validity. */
    valid_from: string & tags.Format<"date-time">;

    /** End datetime for the ticket validity. */
    valid_until: string & tags.Format<"date-time">;

    /** Current usage status of the ticket (unused, used, expired). */
    usage_status: string;

    /** Datetime when ticket was used, nullable if unused. */
    used_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Coupon ticket update record for managing existing coupon ticket usage and
   * details. Supports full or partial update of all coupon ticket properties
   * including usage timing and ownership changes.
   */
  export type IUpdate = {
    /** Associated coupon's unique identifier. */
    shopping_mall_coupon_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Guest user owner ID, nullable for member/seller/admin ownership. */
    guestuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Member user owner ID, nullable for guest/seller/admin ownership. */
    memberuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Seller user owner ID, nullable for guest/member/admin ownership. */
    selleruser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Admin user owner ID, nullable for guest/member/seller ownership. */
    adminuser_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Unique code for this coupon ticket. */
    ticket_code?: string | undefined;

    /** Start datetime for the ticket's validity. */
    valid_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** End datetime for the ticket validity. */
    valid_until?: (string & tags.Format<"date-time">) | null | undefined;

    /** Current usage status of the ticket (unused, used, expired). */
    usage_status?: string | undefined;

    /** Datetime when ticket was used, nullable if unused. */
    used_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Record creation timestamp. */
    created_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Record last update timestamp. */
    updated_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary information of coupon tickets.
   *
   * Provides core coupon ticket data suitable for list display and filtering.
   *
   * Excludes detailed ownership and usage timestamps for brevity.
   */
  export type ISummary = {
    /** Unique coupon ticket identifier. */
    id: string & tags.Format<"uuid">;

    /** Related coupon ID. */
    shopping_mall_coupon_id: string & tags.Format<"uuid">;

    /** Unique ticket code. */
    ticket_code: string;

    /** Usage status of the coupon ticket. */
    usage_status: string;

    /** Creation timestamp of the coupon ticket record. */
    created_at: string & tags.Format<"date-time">;
  };
}
