import { tags } from "typia";

/**
 * Guest user connections to the shopping mall, tracking non-member visitor
 * information per session without authentication credentials. Used for
 * anonymous browsing and session-based identification.
 *
 * This entity records details such as IP address, access URLs, referrer
 * information, user agent strings, and session timestamps. It supports session
 * lifecycle management with start and end times.
 *
 * Guest users do not authenticate with credentials but are tracked for
 * analytics and temporary sessions.
 *
 * The data also supports audit and security monitoring of guest activity in the
 * shopping mall.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallGuestUsers = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** IP address of the guest user connection. */
  ip_address: string;

  /** The access URL the guest used to arrive at the mall. */
  access_url: string;

  /** HTTP referrer URL if available. */
  referrer?: string | null | undefined;

  /** User-Agent string from the guest browser. */
  user_agent?: string | null | undefined;

  /** Timestamp when the guest session started. */
  session_start_at: string & tags.Format<"date-time">;

  /** Timestamp when the guest session ended or expired. */
  session_end_at?: (string & tags.Format<"date-time">) | null | undefined;

  /** Record creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Last update timestamp. */
  updated_at: string & tags.Format<"date-time">;

  /** Timestamp when guest record was logically deleted, if applicable. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IShoppingMallGuestUsers {
  /**
   * Request parameters for filtering, sorting, and pagination of guest user
   * sessions.
   */
  export type IRequest = {
    /** Page number for paginated guest user session list. */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /** Maximum number of results per page. */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /** Column name to sort the results by. */
    sortBy?: string | null | undefined;

    /** Sort direction (ascending or descending). */
    sortDirection?: "asc" | "desc" | null | undefined;

    /** Search keyword for filtering guest user properties. */
    search?: string | null | undefined;

    /** Filter for guest sessions started after this timestamp. */
    session_start_after?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** Filter for guest sessions started before this timestamp. */
    session_start_before?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** Filter guest sessions by status. */
    status?: string | null | undefined;
  };

  /**
   * Update payload for guest user session data. Supports modification of IP
   * address, access URL, referrer, user agent, session timestamps, and
   * logical deletion flag. Optional properties may be omitted if no change is
   * desired.
   */
  export type IUpdate = {
    /** IP address of the guest user connection. */
    ip_address?: string | undefined;

    /** The access URL the guest used to arrive at the mall. */
    access_url?: string | undefined;

    /** HTTP referrer URL if available. */
    referrer?: string | null | undefined;

    /** User-Agent string from the guest browser. */
    user_agent?: string | null | undefined;

    /** Timestamp when the guest session started. */
    session_start_at?: (string & tags.Format<"date-time">) | undefined;

    /** Timestamp when the guest session ended or expired. */
    session_end_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Record creation timestamp. */
    created_at?: (string & tags.Format<"date-time">) | undefined;

    /** Last update timestamp. */
    updated_at?: (string & tags.Format<"date-time">) | undefined;

    /** Timestamp when guest record was logically deleted, if applicable. */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary information of guest user sessions connected to the system. This
   * includes key identification data and timestamps necessary for auditing
   * and brief display.
   */
  export type ISummary = {
    /** Unique identifier representing the guest user's session ID. */
    id: string & tags.Format<"uuid">;

    /** IPv4 or IPv6 address of the guest user connection. */
    ip_address: string;

    /**
     * URL accessed by the guest user upon connection to the shopping mall
     * platform.
     */
    access_url: string;

    /**
     * User-Agent string identifying the guest user's device or browser, if
     * available.
     */
    user_agent?: string | null | undefined;

    /** Timestamp marking the start of the guest user's browsing session. */
    session_start_at: string & tags.Format<"date-time">;

    /**
     * Timestamp marking end of the guest user's browsing session, null if
     * active or unknown.
     */
    session_end_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Timestamp recording when the guest user session record was created in
     * the database.
     */
    created_at: string & tags.Format<"date-time">;
  };
}
