import { tags } from "typia";

/**
 * Records inventory changes with detailed information about stock adjustments
 * and actors responsible for the changes to maintain stock consistency and
 * audit compliance.
 *
 * @author AutoBE - https://github.com/wrtnlabs/autobe
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallInventoryAudit = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /**
   * Reference to the inventory item changed.
   * {@link shopping_mall_inventory.id}
   */
  inventory_id: string & tags.Format<"uuid">;

  /**
   * User or system actor who caused the inventory change.
   * {@link shopping_mall_memberusers.id}, {@link shopping_mall_sellerusers.id},
   * or {@link shopping_mall_adminusers.id}
   */
  actor_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Type of inventory change such as 'addition', 'subtraction', or
   * 'adjustment'.
   */
  change_type: string;

  /** Quantity by which the inventory changed; positive or negative. */
  quantity_changed: number & tags.Type<"int32">;

  /** Optional textual reason for the inventory change. */
  change_reason?: string | null | undefined;

  /** Timestamp when the inventory change was recorded. */
  changed_at: string & tags.Format<"date-time">;
};
export namespace IShoppingMallInventoryAudit {
  /** Page request data */
  export type IRequest = {
    /**
     * Reference to the inventory item changed.
     * {@link shopping_mall_inventory.id}
     */
    inventory_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * User or system actor who caused the inventory change.
     * {@link shopping_mall_memberusers.id},
     * {@link shopping_mall_sellerusers.id}, or
     * {@link shopping_mall_adminusers.id}
     */
    actor_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Type of inventory change such as 'addition', 'subtraction', or
     * 'adjustment'.
     */
    change_type?: string | null | undefined;

    /** Timestamp when the inventory change was recorded, start range. */
    changed_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Timestamp when the inventory change was recorded, end range. */
    changed_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Page number. */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /** Limitation of records per a page. */
    limit?: (number & tags.Type<"int32">) | null | undefined;
  };
}
