import { tags } from "typia";

/**
 * Represents a product inquiry submitted by a customer, including content,
 * privacy, and status information.
 *
 * This entity manages the inquiry's hierarchical relationships and associations
 * with channels, sections, categories, and users.
 *
 * Handles data integrity through soft deletion and auditing with timestamp
 * fields.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallInquiry = {
  /** Primary Key. UUID string identifying the inquiry */
  id: string & tags.Format<"uuid">;

  /** Associated shopping mall sales channel ID (UUID) */
  shopping_mall_channel_id: string & tags.Format<"uuid">;

  /** Associated mall section within channel (UUID or null) */
  shopping_mall_section_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Category classification of inquiry (UUID or null) */
  shopping_mall_category_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Member user ID who posted the inquiry (UUID or null) */
  shopping_mall_memberuserid?:
    | (string & tags.Format<"uuid">)
    | null
    | undefined;

  /** Guest user ID who posted the inquiry (UUID or null) */
  shopping_mall_guestuserid?: (string & tags.Format<"uuid">) | null | undefined;

  /** Parent inquiry ID for hierarchical threading (UUID or null) */
  parent_inquiry_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Title of the inquiry provided by the customer */
  inquiry_title: string;

  /** Detailed message or question content of the inquiry */
  inquiry_body: string;

  /**
   * Indicates if the inquiry is private and accessible only to authorized
   * roles
   */
  is_private: boolean;

  /** Flag indicating if the inquiry has been answered */
  is_answered: boolean;

  /** Current status of the inquiry (e.g., 'open', 'closed', 'pending') */
  status: string;

  /** Timestamp when the inquiry was created (ISO 8601 string) */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp when the inquiry was last updated (ISO 8601 string) */
  updated_at: string & tags.Format<"date-time">;

  /** Soft deletion timestamp; null if not deleted */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IShoppingMallInquiry {
  /**
   * Request parameters to filter, search, sort, and paginate inquiries.
   *
   * Supports complex queries for customer service management and workflow
   * optimizations.
   *
   * @author AutoBE - https://github.com/wrtnlabs/autobe
   * @namespace Inquiries
   */
  export type IRequest = {
    /** Page number for pagination. */
    page?: number | null | undefined;

    /** Limit of records per page. */
    limit?: number | null | undefined;

    /** Filter by channel ID. */
    shopping_mall_channel_id?: string | null | undefined;

    /** Filter by section ID. */
    shopping_mall_section_id?: string | null | undefined;

    /** Filter by category ID. */
    shopping_mall_category_id?: string | null | undefined;

    /** Filter by member user ID. */
    shopping_mall_memberuserid?: string | null | undefined;

    /** Filter by guest user ID. */
    shopping_mall_guestuserid?: string | null | undefined;

    /** Filter by parent inquiry ID. */
    parent_inquiry_id?: string | null | undefined;

    /** Filter by inquiry title with substring matching. */
    inquiry_title?: string | null | undefined;

    /** Filter by inquiry body with substring matching. */
    inquiry_body?: string | null | undefined;

    /** Filter by privacy flag. */
    is_private?: boolean | null | undefined;

    /** Filter by answered flag. */
    is_answered?: boolean | null | undefined;

    /** Filter by status string. */
    status?: string | null | undefined;

    /** Sort field name. */
    sort_by?: string | null | undefined;

    /** Sort direction: "asc" or "desc". */
    sort_direction?: "asc" | "desc" | null | undefined;
  };

  /**
   * Request body for creating a new product inquiry. Includes channel, title,
   * content, privacy flag, and status.
   *
   * Optional properties include section, category, member, guest, and parent
   * inquiry references.
   */
  export type ICreate = {
    /** Associated shopping mall sales channel ID (UUID) */
    shopping_mall_channel_id: string & tags.Format<"uuid">;

    /** Associated mall section within channel (UUID or null) */
    shopping_mall_section_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Category classification of inquiry (UUID or null) */
    shopping_mall_category_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Member user ID who posted the inquiry (UUID or null) */
    shopping_mall_memberuserid?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Guest user ID who posted the inquiry (UUID or null) */
    shopping_mall_guestuserid?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Parent inquiry ID for hierarchical threading (UUID or null) */
    parent_inquiry_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Title of the inquiry provided by the customer */
    inquiry_title: string;

    /** Detailed message or question content of the inquiry */
    inquiry_body: string;

    /**
     * Indicates if the inquiry is private and accessible only to authorized
     * roles
     */
    is_private: boolean;

    /** Flag indicating if the inquiry has been answered */
    is_answered?: boolean | undefined;

    /** Current status of the inquiry (e.g., 'open', 'closed', 'pending') */
    status: string;
  };

  /**
   * Request body for updating a product inquiry. Allows modification of
   * inquiry content, privacy, status, and associations.
   */
  export type IUpdate = {
    /** Associated shopping mall sales channel ID (UUID) */
    shopping_mall_channel_id?: (string & tags.Format<"uuid">) | undefined;

    /** Associated mall section within channel (UUID or null) */
    shopping_mall_section_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Category classification of inquiry (UUID or null) */
    shopping_mall_category_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Member user ID who posted the inquiry (UUID or null) */
    shopping_mall_memberuserid?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Guest user ID who posted the inquiry (UUID or null) */
    shopping_mall_guestuserid?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Parent inquiry ID for hierarchical threading (UUID or null) */
    parent_inquiry_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Title of the inquiry provided by the customer */
    inquiry_title?: string | undefined;

    /** Detailed message or question content of the inquiry */
    inquiry_body?: string | undefined;

    /**
     * Indicates if the inquiry is private and accessible only to authorized
     * roles
     */
    is_private?: boolean | undefined;

    /** Flag indicating if the inquiry has been answered */
    is_answered?: boolean | undefined;

    /** Current status of the inquiry (e.g., 'open', 'closed', 'pending') */
    status?: string | undefined;
  };

  /**
   * Summary information for a product inquiry providing basic identification,
   * visibility, status, and creation date.
   *
   * This summary supports efficient retrieval surfaces such as lists and
   * dashboards, omitting detailed content or relationships.
   */
  export type ISummary = {
    /** Unique inquiry identifier. */
    id: string & tags.Format<"uuid">;

    /** Channel id. */
    shopping_mall_channel_id: string & tags.Format<"uuid">;

    /** Inquiry title. */
    inquiry_title: string;

    /** Flag for private inquiry. */
    is_private: boolean;

    /** Flag for answered status. */
    is_answered: boolean;

    /** Inquiry status. */
    status: string;

    /** Created date-time. */
    created_at: string & tags.Format<"date-time">;
  };
}
