import { tags } from "typia";

/**
 * Detailed information about shopping mall coupons including scope, codes,
 * discounts, validity, and usage.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallCoupon = {
  /**
   * Belonged channel's shopping_mall_channels.id.
   *
   * Uniquely identifies the channel to which this coupon is scoped.
   */
  shopping_mall_channel_id: string;

  /**
   * Unique code identifier for the coupon.
   *
   * Business unique.
   */
  coupon_code: string;

  /**
   * Name of the coupon for display purposes.
   *
   * Brief human readable name.
   */
  coupon_name: string;

  /**
   * Detailed descriptive information about the coupon's purpose.
   *
   * Optional detailed description.
   */
  coupon_description?: string | null | undefined;

  /**
   * Type of discount: 'amount'(fixed amount) or 'percentage' (percentage
   * off).
   *
   * Must be one of exact values.
   */
  discount_type: "amount" | "percentage";

  /** Value of the discount either as amount or percentage. */
  discount_value: number;

  /**
   * Maximum discount amount allowed for this coupon.
   *
   * Nullable. Caps the maximum discount applied.
   */
  max_discount_amount?: number | null | undefined;

  /**
   * Minimum order amount required to apply this coupon.
   *
   * Nullable.
   */
  min_order_amount?: number | null | undefined;

  /**
   * Maximum number of times this coupon can be used across all customers.
   *
   * Nullable integer.
   */
  usage_limit?: (number & tags.Type<"int32">) | null | undefined;

  /**
   * Maximum number of times this coupon can be used by one customer.
   *
   * Nullable integer.
   */
  per_customer_limit?: (number & tags.Type<"int32">) | null | undefined;

  /**
   * Start date and time of coupon validity period in ISO 8601 datetime
   * format.
   */
  start_date: string & tags.Format<"date-time">;

  /** End date and time of coupon validity period in ISO 8601 datetime format. */
  end_date: string & tags.Format<"date-time">;

  /** Status of the coupon, e.g., 'active', 'paused', 'expired'. */
  status: string;
};
export namespace IShoppingMallCoupon {
  /** Request parameters for filtering, sorting, and pagination of coupons. */
  export type IRequest = {
    /** Optional filter for coupon code. */
    coupon_code?: string | null | undefined;

    /** Optional filter for coupon name. */
    coupon_name?: string | null | undefined;

    /** Optional filter for coupon status. */
    status?: string | null | undefined;

    /** Optional pagination page number. */
    page?: number | null | undefined;

    /** Optional pagination limit per page. */
    limit?: number | null | undefined;

    /** Optional filter by start date (ISO 8601 string). */
    start_date_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Optional filter by end date (ISO 8601 string). */
    end_date_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Optional sort field. */
    order_by?: string | null | undefined;
  };

  /** Payload needed to create a new shopping mall coupon. */
  export type ICreate = {
    /**
     * Channel ID where this coupon applies.
     *
     * Required.
     */
    shopping_mall_channel_id: string;

    /**
     * Unique coupon code.
     *
     * Required.
     */
    coupon_code: string;

    /**
     * Display name of the coupon.
     *
     * Required.
     */
    coupon_name: string;

    /**
     * Descriptive details of the coupon.
     *
     * Optional.
     */
    coupon_description?: string | null | undefined;

    /**
     * Discount type, must be 'amount' or 'percentage'.
     *
     * Required.
     */
    discount_type: "amount" | "percentage";

    /**
     * Discount value.
     *
     * Required.
     */
    discount_value: number;

    /** Optional maximum discount amount. */
    max_discount_amount?: number | null | undefined;

    /** Optional minimum order amount required. */
    min_order_amount?: number | null | undefined;

    /** Optional usage limit total. */
    usage_limit?: (number & tags.Type<"int32">) | null | undefined;

    /** Optional usage limit per customer. */
    per_customer_limit?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Start of validity period in ISO 8601 datetime format.
     *
     * Required.
     */
    start_date: string & tags.Format<"date-time">;

    /**
     * End of validity period in ISO 8601 datetime format.
     *
     * Required.
     */
    end_date: string & tags.Format<"date-time">;

    /**
     * Coupon status.
     *
     * Required.
     */
    status: string;
  };

  /** Payload to update an existing shopping mall coupon with optional fields. */
  export type IUpdate = {
    /**
     * Channel ID where this coupon applies.
     *
     * Optional.
     */
    shopping_mall_channel_id?: string | null | undefined;

    /**
     * Coupon code.
     *
     * Optional.
     */
    coupon_code?: string | null | undefined;

    /**
     * Coupon display name.
     *
     * Optional.
     */
    coupon_name?: string | null | undefined;

    /**
     * Coupon description.
     *
     * Optional.
     */
    coupon_description?: string | null | undefined;

    /** Discount type; 'amount' or 'percentage'. */
    discount_type?: "amount" | "percentage" | null | undefined;

    /**
     * Discount value.
     *
     * Optional.
     */
    discount_value?: number | null | undefined;

    /**
     * Maximum discount amount.
     *
     * Optional.
     */
    max_discount_amount?: number | null | undefined;

    /**
     * Minimum order amount.
     *
     * Optional.
     */
    min_order_amount?: number | null | undefined;

    /**
     * Usage limit.
     *
     * Optional.
     */
    usage_limit?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Per customer usage limit.
     *
     * Optional.
     */
    per_customer_limit?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Validity start date.
     *
     * Optional.
     */
    start_date?: string | null | undefined;

    /**
     * Validity end date.
     *
     * Optional.
     */
    end_date?: string | null | undefined;

    /**
     * Coupon status.
     *
     * Optional.
     */
    status?: string | null | undefined;
  };

  /**
   * Summary information for coupons.
   *
   * Offers concise coupon data for list views and search results without
   * exposing full details.
   */
  export type ISummary = {
    /** Unique coupon identifier. */
    id: string & tags.Format<"uuid">;

    /** Coupon code. */
    coupon_code: string;

    /** Coupon name. */
    coupon_name: string;

    /** Coupon discount type. */
    discount_type: string;

    /** Discount value. */
    discount_value: number;

    /** Coupon status. */
    status: string;

    /** Creation date. */
    created_at: string & tags.Format<"date-time">;
  };
}
