import { tags } from "typia";

/**
 * Order items belonging to a specific shopping mall order. Each item references
 * the product sale snapshot for consistency and tracks quantity, price, and
 * status. This supporting entity enables detailed management of individual
 * order contents, including returns and exchanges.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallOrderItem = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** Belonged order for this item. {@link shopping_mall_orders.id}. */
  shopping_mall_order_id: string & tags.Format<"uuid">;

  /**
   * Referenced sale snapshot for the product in this order item.
   * {@link shopping_mall_sale_snapshots.id}.
   */
  shopping_mall_sale_snapshot_id: string & tags.Format<"uuid">;

  /** Quantity ordered of this product item. */
  quantity: number & tags.Type<"int32">;

  /** Price per unit of the product item at order time. */
  price: number;

  /**
   * Current status of this order item such as 'pending', 'shipped',
   * 'returned'.
   */
  order_item_status: string;

  /** Timestamp when this order item was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp when this order item was last updated. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IShoppingMallOrderItem {
  /** Request body schema to create a new order item for a shopping mall order. */
  export type ICreate = {
    /** Belonged order for this item. {@link shopping_mall_orders.id}. */
    shopping_mall_order_id: string & tags.Format<"uuid">;

    /**
     * Referenced sale snapshot for the product in this order item.
     * {@link shopping_mall_sale_snapshots.id}.
     */
    shopping_mall_sale_snapshot_id: string & tags.Format<"uuid">;

    /** Quantity ordered of this product item. */
    quantity: number & tags.Type<"int32">;

    /** Price per unit of the product item at order time. */
    price: number;

    /**
     * Current status of this order item such as 'pending', 'shipped',
     * 'returned'.
     */
    order_item_status: string;
  };

  /**
   * Request body schema to update an existing order item for a shopping mall
   * order.
   */
  export type IUpdate = {
    /** Belonged order for this item. {@link shopping_mall_orders.id}. */
    shopping_mall_order_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Referenced sale snapshot for the product in this order item.
     * {@link shopping_mall_sale_snapshots.id}.
     */
    shopping_mall_sale_snapshot_id?: (string & tags.Format<"uuid">) | undefined;

    /** Quantity ordered of this product item. */
    quantity?: (number & tags.Type<"int32">) | undefined;

    /** Price per unit of the product item at order time. */
    price?: number | undefined;

    /**
     * Current status of this order item such as 'pending', 'shipped',
     * 'returned'.
     */
    order_item_status?: string | undefined;
  };
}
