import { tags } from "typia";

/**
 * Business entity representing customers orders. Includes references to the
 * member user who placed the order, sales channel, spatial section, and status
 * fields.
 *
 * Tracks order and payment status, total pricing, creation and update
 * timestamps, and soft deletion flag.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallOrder = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /**
   * Belonged member user who placed the order.
   * {@link shopping_mall_memberusers.id}.
   */
  shopping_mall_memberuser_id: string & tags.Format<"uuid">;

  /**
   * Sales channel through which the order was placed.
   * {@link shopping_mall_channels.id}.
   */
  shopping_mall_channel_id: string & tags.Format<"uuid">;

  /**
   * Section representing spatial grouping of the order.
   * {@link shopping_mall_sections.id}.
   */
  shopping_mall_section_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** Unique business identifier for the order. */
  order_code: string;

  /**
   * Current status of the order such as 'pending', 'confirmed', 'shipped',
   * 'delivered', 'cancelled'.
   */
  order_status: string;

  /** Current status of payment such as 'pending', 'paid', 'cancelled'. */
  payment_status: string;

  /** Total price of the order including all items and discounts. */
  total_price: number;

  /** Timestamp for when the order was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp for when the order was last updated. */
  updated_at: string & tags.Format<"date-time">;

  /** Timestamp for soft deletion; null if not deleted. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IShoppingMallOrder {
  /**
   * Request body for creating a new order.
   *
   * Includes references to member user, channel, section, and essential order
   * details including order code and status.
   *
   * All fields are required except the section ID which may be null.
   */
  export type ICreate = {
    /**
     * Belonged member user who placed the order.
     * {@link shopping_mall_memberusers.id}.
     */
    shopping_mall_memberuser_id: string & tags.Format<"uuid">;

    /**
     * Sales channel through which the order was placed.
     * {@link shopping_mall_channels.id}.
     */
    shopping_mall_channel_id: string & tags.Format<"uuid">;

    /**
     * Section representing spatial grouping of the order.
     * {@link shopping_mall_sections.id}.
     */
    shopping_mall_section_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Unique business identifier for the order. */
    order_code: string;

    /**
     * Current status of the order such as 'pending', 'confirmed',
     * 'shipped', 'delivered', 'cancelled'.
     */
    order_status: string;

    /** Current status of payment such as 'pending', 'paid', 'cancelled'. */
    payment_status: string;

    /** Total price of the order including all items and discounts. */
    total_price: number;
  };

  /**
   * Request body for updating an existing order.
   *
   * All fields are optional allowing partial updates.
   *
   * Includes soft deletion timestamp to mark logical deletion.
   */
  export type IUpdate = {
    /**
     * Belonged member user who placed the order.
     * {@link shopping_mall_memberusers.id}.
     */
    shopping_mall_memberuser_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Sales channel through which the order was placed.
     * {@link shopping_mall_channels.id}.
     */
    shopping_mall_channel_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Section representing spatial grouping of the order.
     * {@link shopping_mall_sections.id}.
     */
    shopping_mall_section_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Unique business identifier for the order. */
    order_code?: string | undefined;

    /**
     * Current status of the order such as 'pending', 'confirmed',
     * 'shipped', 'delivered', 'cancelled'.
     */
    order_status?: string | undefined;

    /** Current status of payment such as 'pending', 'paid', 'cancelled'. */
    payment_status?: string | undefined;

    /** Total price of the order including all items and discounts. */
    total_price?: number | undefined;

    /** Timestamp for soft deletion; null if not deleted. */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
