import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { post__shoppingMall_sellerUser_sales } from "../../../../providers/post__shoppingMall_sellerUser_sales";
import { SelleruserAuth } from "../../../../decorators/SelleruserAuth";
import { SelleruserPayload } from "../../../../decorators/payload/SelleruserPayload";
import { patch__shoppingMall_sellerUser_sales } from "../../../../providers/patch__shoppingMall_sellerUser_sales";
import { get__shoppingMall_sellerUser_sales_$saleId } from "../../../../providers/get__shoppingMall_sellerUser_sales_$saleId";
import { put__shoppingMall_sellerUser_sales_$saleId } from "../../../../providers/put__shoppingMall_sellerUser_sales_$saleId";
import { delete__shoppingMall_sellerUser_sales_$saleId } from "../../../../providers/delete__shoppingMall_sellerUser_sales_$saleId";

import { IShoppingMallSale } from "../../../../api/structures/IShoppingMallSale";
import { IPageIShoppingMallSale } from "../../../../api/structures/IPageIShoppingMallSale";

@Controller("/shoppingMall/sellerUser/sales")
export class ShoppingmallSelleruserSalesController {
  /**
   * Create a new sales product record.
   *
   * Register a new product for sale in the shopping mall.
   *
   * Restricted to users with 'sellerUser' role.
   *
   * Input includes product channel, seller, unique code, status, name, optional
   * description, and base price.
   *
   * Unique code is validated.
   *
   * On successful creation, returns the created product data.
   *
   * Handles errors including validation failure and code conflict.
   *
   * @param connection
   * @param body Creation data for new sales product
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @SelleruserAuth()
    sellerUser: SelleruserPayload,
    @TypedBody()
    body: IShoppingMallSale.ICreate,
  ): Promise<IShoppingMallSale> {
    try {
      return await post__shoppingMall_sellerUser_sales({
        sellerUser,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Search and list shopping mall sales products.
   *
   * Get a filtered and paginated list of sales products in the shopping mall.
   *
   * This endpoint supports multiple filters like product name, seller, channel,
   * and status.
   *
   * Search results include active and archived products with audit and status
   * tracking.
   *
   * Access is restricted to users with 'adminUser' or 'sellerUser' roles.
   *
   * Validation of paging and filters is implemented.
   *
   * @param connection
   * @param body Search criteria and pagination for sales products
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @SelleruserAuth()
    sellerUser: SelleruserPayload,
    @TypedBody()
    body: IShoppingMallSale.IRequest,
  ): Promise<IPageIShoppingMallSale.ISummary> {
    try {
      return await patch__shoppingMall_sellerUser_sales({
        sellerUser,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed sales product by ID.
   *
   * Get a sales product's full information by saleId.
   *
   * Access is restricted to authorized users with roles 'adminUser' or
   * 'sellerUser'.
   *
   * Returns comprehensive product details including audit timestamps.
   *
   * Handles errors for invalid or missing product IDs.
   *
   * @param connection
   * @param saleId Unique identifier of the sales product
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":saleId")
  public async at(
    @SelleruserAuth()
    sellerUser: SelleruserPayload,
    @TypedParam("saleId")
    saleId: string & tags.Format<"uuid">,
  ): Promise<IShoppingMallSale> {
    try {
      return await get__shoppingMall_sellerUser_sales_$saleId({
        sellerUser,
        saleId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update a sales product's information.
   *
   * Modify details of a sales product identified by saleId.
   *
   * Authorization is required for 'adminUser' and 'sellerUser' roles.
   *
   * Update payload can modify channel, section, seller id, status, name,
   * description, and price.
   *
   * Validates inputs strictly.
   *
   * Returns updated product info or errors.
   *
   * @param connection
   * @param saleId Unique identifier of the sales product to update
   * @param body Update data for sales product
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":saleId")
  public async update(
    @SelleruserAuth()
    sellerUser: SelleruserPayload,
    @TypedParam("saleId")
    saleId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IShoppingMallSale.IUpdate,
  ): Promise<IShoppingMallSale> {
    try {
      return await put__shoppingMall_sellerUser_sales_$saleId({
        sellerUser,
        saleId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a shopping mall sale product by its ID.
   *
   * This API endpoint allows a sellerUser or adminUser to permanently delete a
   * product sale record identified by its unique saleId. The operation directly
   * removes the sale entry from the shopping_mall_sales table. Cascade deletion
   * ensures that associated sale snapshots, sale units, and inventory items are
   * removed to prevent orphaned records.
   *
   * Only users with 'sellerUser' or 'adminUser' roles have the authority to
   * perform this deletion due to the irreversible nature of the operation and
   * its impact on product catalogs and order consistency. Attempts by
   * unauthorized roles will be rejected.
   *
   * Upon successful deletion, no response body is returned, but appropriate
   * HTTP status codes communicate the result. Error handling covers cases such
   * as non-existent saleId or insufficient permissions. This operation removes
   * product data permanently and is not reversible through application logic.
   *
   * @param connection
   * @param saleId Unique identifier of the target sale product
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":saleId")
  public async erase(
    @SelleruserAuth()
    sellerUser: SelleruserPayload,
    @TypedParam("saleId")
    saleId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await delete__shoppingMall_sellerUser_sales_$saleId({
        sellerUser,
        saleId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
