import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallSellerUser } from "../../../../../../structures/IShoppingMallSellerUser";

/**
 * Confirm and apply new password for seller user password reset.
 *
 * This API operation confirms the password reset request by verifying the reset
 * token and setting the new password for the seller user.
 *
 * It validates token authenticity, expiration, and associated user, then
 * updates the password securely.
 *
 * This operation finalizes the password recovery workflow complementing the
 * reset request initiation.
 *
 * Secure handling of token and password hashing is mandatory.
 *
 * @param props.connection
 * @param props.body Seller user password reset confirmation including reset
 *   token and new password, following
 *   IShoppingMallSellerUser.IResetPasswordConfirm structure.
 * @path /auth/sellerUser/password/reset/confirm
 * @accessor api.functional.auth.sellerUser.password.reset.confirm.confirmPasswordReset
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function confirmPasswordReset(
  connection: IConnection,
  props: confirmPasswordReset.Props,
): Promise<void> {
  return true === connection.simulate
    ? confirmPasswordReset.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...confirmPasswordReset.METADATA,
          path: confirmPasswordReset.path(),
          status: null,
        },
        props.body,
      );
}
export namespace confirmPasswordReset {
  export type Props = {
    /**
     * Seller user password reset confirmation including reset token and new
     * password, following IShoppingMallSellerUser.IResetPasswordConfirm
     * structure.
     */
    body: IShoppingMallSellerUser.IResetPasswordConfirm;
  };
  export type Body = IShoppingMallSellerUser.IResetPasswordConfirm;

  export const METADATA = {
    method: "POST",
    path: "/auth/sellerUser/password/reset/confirm",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/sellerUser/password/reset/confirm";
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: confirmPasswordReset.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: confirmPasswordReset.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
