import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallCoupon } from "../../../../structures/IShoppingMallCoupon";
import { IPageIShoppingMallCoupon } from "../../../../structures/IPageIShoppingMallCoupon";

/**
 * Search and list discount coupons.
 *
 * Search and retrieve discount coupons with advanced filtering and pagination
 * capabilities.
 *
 * This endpoint allows administrators, sellers, and members to access available
 * coupons subject to their permissions.
 *
 * Coupons support amount and percentage discounts with conditions and
 * expiration dates.
 *
 * The underlying data originates from the shopping_mall_coupons table managing
 * coupon metadata, conditions, and usage logs.
 *
 * @param props.connection
 * @param props.body Coupon search criteria
 * @path /shoppingMall/sellerUser/coupons
 * @accessor api.functional.shoppingMall.sellerUser.coupons.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Coupon search criteria */
    body: IShoppingMallCoupon.IRequest;
  };
  export type Body = IShoppingMallCoupon.IRequest;
  export type Response = IPageIShoppingMallCoupon.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/sellerUser/coupons",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/sellerUser/coupons";
  export const random = (): IPageIShoppingMallCoupon.ISummary =>
    typia.random<IPageIShoppingMallCoupon.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve coupon detail by ID.
 *
 * Get detailed coupon information by coupon ID.
 *
 * Accessible by administrators, sellers, and members.
 *
 * Provides complete coupon properties, status, and usage rules.
 *
 * @param props.connection
 * @param props.couponId Unique ID of the coupon
 * @path /shoppingMall/sellerUser/coupons/:couponId
 * @accessor api.functional.shoppingMall.sellerUser.coupons.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique ID of the coupon */
    couponId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCoupon;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/sellerUser/coupons/:couponId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/sellerUser/coupons/${encodeURIComponent(props.couponId ?? "null")}`;
  export const random = (): IShoppingMallCoupon =>
    typia.random<IShoppingMallCoupon>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("couponId")(() => typia.assert(props.couponId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
