import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallSellerResponse } from "../../../../structures/IShoppingMallSellerResponse";
import { IPageIShoppingMallSellerResponse } from "../../../../structures/IPageIShoppingMallSellerResponse";

/**
 * Create new seller response.
 *
 * Create a new seller response entry.
 *
 * Request body includes response text, author user ID, privacy, and status.
 *
 * Only authorized users with seller or admin roles may create responses.
 *
 * Returns the created seller response record.
 *
 * @param props.connection
 * @param props.body New seller response data
 * @path /shoppingMall/adminUser/sellerResponses
 * @accessor api.functional.shoppingMall.adminUser.sellerResponses.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /** New seller response data */
    body: IShoppingMallSellerResponse.ICreate;
  };
  export type Body = IShoppingMallSellerResponse.ICreate;
  export type Response = IShoppingMallSellerResponse;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/adminUser/sellerResponses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/adminUser/sellerResponses";
  export const random = (): IShoppingMallSellerResponse =>
    typia.random<IShoppingMallSellerResponse>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * List seller responses with filtering options.
 *
 * Retrieve seller responses with pagination and filtering capabilities.
 *
 * Supports filtering by content, privacy, status, and author.
 *
 * Access restricted to members with proper seller or admin roles.
 *
 * Used to manage official seller communications to customers.
 *
 * @param props.connection
 * @param props.body Pagination and filter criteria for seller responses
 * @path /shoppingMall/adminUser/sellerResponses
 * @accessor api.functional.shoppingMall.adminUser.sellerResponses.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Pagination and filter criteria for seller responses */
    body: IShoppingMallSellerResponse.IRequest;
  };
  export type Body = IShoppingMallSellerResponse.IRequest;
  export type Response = IPageIShoppingMallSellerResponse;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/adminUser/sellerResponses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/adminUser/sellerResponses";
  export const random = (): IPageIShoppingMallSellerResponse =>
    typia.random<IPageIShoppingMallSellerResponse>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Get details of a specific seller response.
 *
 * Retrieve detailed information of a seller response identified by id.
 *
 * Includes response content, author identification, privacy settings, status,
 * and metadata.
 *
 * Authorization required for seller or admin users.
 *
 * Supports management and audit of seller communications.
 *
 * @param props.connection
 * @param props.id Unique identifier of the seller response
 * @path /shoppingMall/adminUser/sellerResponses/:id
 * @accessor api.functional.shoppingMall.adminUser.sellerResponses.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the seller response */
    id: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallSellerResponse;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/adminUser/sellerResponses/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/adminUser/sellerResponses/${encodeURIComponent(props.id ?? "null")}`;
  export const random = (): IShoppingMallSellerResponse =>
    typia.random<IShoppingMallSellerResponse>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
