import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallCouponLog } from "../../../../structures/IShoppingMallCouponLog";

/**
 * Retrieve coupon log details by unique ID.
 *
 * Retrieve detailed coupon log information by specifying the unique coupon log
 * ID. This operation fetches all recorded activities related to coupon tickets,
 * including issuance, usage, and expirations.
 *
 * Access to coupon logs is restricted for security and compliance purposes.
 * Roles such as adminUser have the necessary permissions to query these logs.
 *
 * The response includes comprehensive audit data tied to coupon tickets, with
 * user references where applicable. Errors return not found if the ID is
 * invalid or does not exist.
 *
 * @param props.connection
 * @param props.id Unique identifier of the coupon log
 * @path /shoppingMall/adminUser/couponLogs/:id
 * @accessor api.functional.shoppingMall.adminUser.couponLogs.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the coupon log */
    id: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCouponLog;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/adminUser/couponLogs/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/adminUser/couponLogs/${encodeURIComponent(props.id ?? "null")}`;
  export const random = (): IShoppingMallCouponLog =>
    typia.random<IShoppingMallCouponLog>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
